### ISSUE TITLE
Touch input not rotated in Gnome or Gdm (Ubuntu 17.04)

### ISSUE THREAD

**Issue by jeanblanchard** [nexus511/gpd-ubuntu-packages#14]
STR (from memory, I hope I don't forget anything):
- Install the Ubuntu 17.04 image from here
- `apt update && apt full-upgrade`
- `apt install ubuntu-gnome-desktop` (Choosing GDM at the prompt)
- `apt install gpdpocket-gnome-config`
- disable Wayland in /etc/gdm3/custom.conf
- reboot

At first the screen is not rotated in GDM or Gnome, but I can configure it in gnome-settings, which fixes GDM too.
But the input transformation matrix is not applied in either.
If I re-enable Lightdm, the input is still fine in a Unity session, but not in a Gnome session. With xinput I can confirm that the "Coordinate Transformation Matrix" is applied in Unity but not in Gnome.

My understanding is that this is supposed handled by Xorg, so I don't get where this is coming from...

I am currently downloading the new Ubuntu-Gnome image, I'll see if that changes anything...

**Comment by nexus511** [comment]
No, it gnome seems to override the rotation. So X11 configuration itself does not help.

I might be able to test it myself tomorrow.

**Comment by jeanblanchard** [comment]
I can confirm that in the live ubuntu-gnome image, the touch inputs are not rotated (but the screen orientation is correct on boot). I'm not going to reinstall after all, that's enough installs already for 24h...

**Comment by nexus511** [comment]
Well, reinstalling would not have any value. If it does not work in the live-image, it will not work ootb in the installed version.

As there have been some requests on supporting gnome, I will take a look at it. There is most likely just some configuration missing. My understanding is that gdm will be running wayland and thus the X11 configurations will not (all) be present.

We recently added configurations for screen-rotation working on wayland, but I guess that we need something else there, to get the touch oriented properly.

Useful hints or comments are always welcome though.

**Comment by nexus511** [comment]
Should be closed with Hotel release.
