### ISSUE TITLE
Hotel release linux headers gives errors when creating vmware modules

### ISSUE THREAD

**Issue by snazzybunny** [nexus511/gpd-ubuntu-packages#19]
This could be vmware related but I installed the latest hotel release and did a sudo apt update and then sudo apt upgrade. How do I check if the kernel headers are installed? 

Maybe vmware cannot be installed for this kernel version as I am getting the same errors as last time. One of the error output lines is `<builtin>: recipe for target 'driver.o' failed.` Any chance you could try to install vmware and see if you get the same results? Thanks.

**Comment by nexus511** [comment]
Kernel headers are normally not installed automatically. You need to install **kernel-headers-generic** or at least check, if **kernel-headers-generic** is installed.

I for myself will not install *vmware* on my device as I am not planning to provide support for all proprietary software out there. I have actually tested *KVM* which has build-in support and works well on the *GPD Pocket*.

If anyone can provide a useful PR that fixes issues with *vmware*, please feel free to submit one.

**Comment by snazzybunny** [comment]
VMware is confirmed to work now. I just assumed it would install the headers when I did an upgrade. Thanks.


sudo apt install linux-headers-generic
sudo su
cd /usr/lib/vmware/modules/source	
tar xf vmnet.tar
cd vmnet-only
wget https://communities.vmware.com/servlet/JiveServlet/download/2688951-180357/VMware-Workstation-12.5.7-kernel4.13-atomic-inc.patch.zip
unzip VMware-Workstation-12.5.7-kernel4.13-atomic-inc.patch.zip
patch < VMware-Workstation-12.5.7-kernel4.13-atomic-inc.patch
make
cd ..
tar xf vmmon.tar
cd vmmon-only
make
cd ..
cp vmmon.o /lib/modules/`uname -r`/kernel/drivers/misc/vmmon.ko
cp vmnet.o /lib/modules/`uname -r`/kernel/drivers/misc/vmnet.ko
depmod -a
/etc/init.d/vmware restart

**Comment by nexus511** [comment]
Great! Thank you for sharing the solution.

I'll close it then as it should be easy to find the ticket if anyone else reaches out with problems.
