### ISSUE TITLE
xfce  can not touch close window of the close button

### ISSUE THREAD

**Issue by diandengs** [nexus511/gpd-ubuntu-packages#23]
ubuntu16.04 use xfce exist touch bug, can not touch the right corner of the click button, zoom in and out can not operate, can not close the window, can not touch the title bar to move the window.

**Comment by nexus511** [comment]
(Multi-)touch support is provided by touchegg on the device. It allows only a limited set of features. Please look into the feature description and configuration guide. You find information on the project in its github repository:

    https://github.com/JoseExposito/touchegg
