### ISSUE TITLE
If I need BT, can I just install the latest hansdegoede kernel?

### ISSUE THREAD

**Issue by snazzybunny** [nexus511/gpd-ubuntu-packages#36]
So I was wondering if I could install the hansdegoede kernel side by side with the current kernel installed from your gpd-ubuntu-packages? Will it ruin anything? I don't want to reinstall everything again but I do want to have BT working :O. Thanks!

**Comment by nexus511** [comment]
Yes you can.

You need to cleanup it manually afterwards though.
