### ISSUE TITLE
Audio crackling resolution

### ISSUE THREAD

**Issue by cawilliamson** [nexus511/gpd-ubuntu-packages#38]
Hey nexus511!

There is finally positive news on the audio problems with the GPD Pocket!

https://bugzilla.kernel.org/show_bug.cgi?id=196351

In short:
- Update to the latest version of the kernel provided by hans
- Set the CONFIG_INTEL_ATOMISP value to 'n' (not actually needed)

According to the bugzilla report above - this appears to resolve the issue with no adverse side effects. There is also some requests on there from people running your image asking for you to update to the latest hans kernel since it also appears to resolve bluetooth issues, etc.

Thanks for the awesome work and keep it up man! 👍 

Chris.

**Comment by nexus511** [comment]
Hm. I need to check, if this is already in the current kernel.

Audio has been fine for me for a while as long as I do not load any virtualization modules. But I will double check this later. Thanks for hinting.

**Comment by nexus511** [comment]
@cawilliamson Ah. I never had CONFIG_INTEL_ATOMISP set on my kernels but I will check, if the patch for sound/soc/codecs/rt5645.c is there.

**Comment by nexus511** [comment]
Okay. The patches are already in there but still: I did not use Hans configuration at all. The stock Ubuntu configuration did not cause any audio crackling on my device since I switched to it.

The crackling however still reappears, when I install KVM modules. I have had it back within the system when I used Hans original kernel with his configuration two days ago. After removing all unneeded stuff from it, is was gone again.

**Comment by snazzybunny** [comment]
Does this fix bluetooth audio? Every few seconds it would go out of sink and then sync up again. Thanks!

**Comment by cawilliamson** [comment]
@snazzybunny Not sure man - I haven't used BT audio although the latest kernel from hans does have a lot of BT improvements from what I understand so probably worth testing and reporting back if you still face the issue. 👍

**Comment by cawilliamson** [comment]
@nexus511 - I see the new kernel - cheers! I hadn't powered on my GPD Pocket in a little while - personal life stuff got in the way - blah! :)

Happy to close this one from my end - just leaving it open for now so snazzy can report back on the BT situation.

**Comment by nexus511** [comment]
@cawilliamson Ah. Thank's for reporting back. I close this then.

My understanding is that there are bluetooth audio issues somewhere in the ubuntu bluetooth stack and that those are not explicitly related to the GPD pocket. It is also completely unrelated to this issue, so I close this.

@snazzybunny If you have the feeling that we should have a bug on this, please just open a new, more specific issue but maybe make sure that you checkout the reddit thread on the project first as I remember that there has been a discussion about that somewhere and a hint that it is actually related to the configuration utility on some ubuntu versions.

**Comment by Herst** [comment]
Concerning bluetooth audio quality, there are certain situations in which switching to a better audio codecs (A2DP) does not work, caused e.g. by accessibility features of GDM, see <https://wiki.debian.org/BluetoothUser/a2dp#Refused_to_switch_profile_to_a2dp_sink:_Not_connected> for workarounds.

**Comment by nexus511** [comment]
@Herst ah. I remember something about GDM, yes. Thank you very much for your input on this!
