### ISSUE TITLE
Installation failed while using the whole disk

### ISSUE THREAD

**Issue by giviz** [nexus511/gpd-ubuntu-packages#43]
Hi

I've tried the xubuntu 17 in dual boot with the default windows installation and it was working fine, but I wasn't able to use the filesystem encryption (it was disabled during the install process).

So I've tried the install with the full disk use that erase everything and it failed each time at the same step : Checking for packages to install...

I've also tried the full disk without encryption and it failed there too.

Sadly there is no more log than that :/

Any idea how to fix that ?

**Comment by giviz** [comment]
I've tried with the ubuntu 17 iso too, same issue at the same step :(

**Comment by giviz** [comment]
There is a box that can be opened to view the console during the install process, here is the log at the time of the crash.
It seems that it was trying to update something from online repo, so I tried the installation again with wifi connected, but it still crashed.

I'm not sure if it's related to your custom packages or not.

![unadjustednonraw_thumb_31ace](https://user-images.githubusercontent.com/3670552/32112614-07d94484-bb3e-11e7-9016-6bedb670d26f.jpg)
![unadjustednonraw_thumb_31ad9](https://user-images.githubusercontent.com/3670552/32112617-0850e304-bb3e-11e7-9e24-90821e338aa8.jpg)
![unadjustednonraw_thumb_31adf](https://user-images.githubusercontent.com/3670552/32112618-089d2872-bb3e-11e7-9402-6a51cefa419a.jpg)

**Comment by giviz** [comment]
Last piece of log I've been able to grab is the bug report that is sent after the crash to the ubuntu team : 

![img_6947](https://user-images.githubusercontent.com/3670552/32114999-7098ed88-bb45-11e7-8cff-aad8bcdd9356.jpg)
![img_6948](https://user-images.githubusercontent.com/3670552/32115000-70de18cc-bb45-11e7-9b2e-09029eb9d7bc.jpg)

I'll try to install the official ubuntu release to see if I have the same issue.

**Comment by nexus511** [comment]
That is odd and should not happen (I have never heard about that issue).

I am in fact using Xubuntu 16.04 with full disk encryption and it boots quite well. I guess you are using the "2017-09-04" build?

Edit: Did you try installing without Wifi enabled? If so, it might be an idea to try.

**Comment by giviz** [comment]
I've tried : 
xubuntu-17.04-desktop-amd64_gpdpocket_2017-09-04
ubuntu-17.04-desktop-amd64_gpdpocket_2017-09-04

with and without wifi

I've not tried the 16.04, I'll download it, try and update you :)

**Comment by giviz** [comment]
Same issue with the 16.04 :(
I'll try the Gpd version now.

**Comment by giviz** [comment]
Well, same issue with the Gpd version.

That might be an issue with the hard drive.
I'll try to reformat it and to reinstall the default windows OS.

Doesn't seems to be relative to your script anyways.
Thanks

**Comment by giviz** [comment]
Final note : The issue was with the usb flash drive used for the installation, I've used an other one and it worked :)

**Comment by nexus511** [comment]
Ah. Good to hear. I could have though about that earlier.

**Comment by Herst** [comment]
Ah, explains the "I/O error"s.

**Comment by giviz** [comment]
Yep that the hint that pushed me to try an other usb key actually ;)
