### ISSUE TITLE
ubuntu-gnome-desktop not working

### ISSUE THREAD

**Issue by nexus511** [nexus511/gpd-ubuntu-packages#6]
Based on a reddit discussion, rotation does not work on ubuntu-gnome-desktop:

> I've removed monitors.xml and install gpdpocket-gnome-config, lightdm is rotated ok now, but gnome display is not rotated (i've just installed ubuntu-gnome-desktop over ubuntu 17.04 iso I've downloaded for your website). If I change rotation in gnome settings, the screen itself is rotated, but the touches remains unrotated (I mean touch events goes unrotated)

As this is not a targeted default desktop, I will only work on that, if I find some spare time. Pull requests are that fix or hints that help fixing it are always welcome.

**Comment by m-dango** [comment]
I might poke around on the desktop environment and see what I can come up with. I was trying to get the Ubuntu GNOME flavor built myself, but did not get very far unfortunately 😓

No rush as it's quite a while off, but it's worth nothing that GNOME 3 will be replacing Unity in 18.04 LTS.

**Comment by Xianbei233** [comment]
I use the ubuntu-gnome-desktop over ubuntu 17.04 and its rotation works well for i using the ansible that cawilliamson made. You can see his works to get the solution.

**Comment by m-dango** [comment]
Going from a fresh installation of the Ubuntu 16.04.3 image, I did `sudo apt update`, `sudo apt upgrade`, `sudo apt install ubuntu-gnome-desktop`.

It appears that gdm3 does not like the monitors.xml config for lightdm. Modifying monitors.xml in GNOME via the GUI adds a new XML element for configuration, and then copying it over to `/var/lib/gdm3/.config/monitors.xml` fixes the rotation of the gdm3 login screen. Still poking around to see if monitors.xml can be avoided.

I haven't encountered any issues with touch/rotation not lining up.

**Comment by nexus511** [comment]
Ah. ubuntu-gnome-desktop pulls gdm? Than it makes sense that it does not work.

@mienaikage cawilliamson used a script for rotation which I removed as it failed sometimes. As gnome/unity do not honor the xorg.conf, I deployed monitors.xml instead. i would be happy to get it removed.

Thank you for your help so far.

**Comment by nexus511** [comment]
@mienaikage Would something like this work?

https://github.com/nexus511/gpd-ubuntu-packages/compare/bugfix/gnome-desktop-rotation

It would copy the monitors.xml to the gdm3 directory. I have been aware of this change for gdm3 but not that it might be necessary for ubuntu-gnome-desktop.

Is there anything else that remains broken or does this fix the rotation for gdm3 and gnome in one shot?

**Comment by m-dango** [comment]
Almost. `monitors.xml` needs an extra configuration because a single one doesn't seem to work across both lightdm and gdm3. I've put the changes in https://github.com/nexus511/gpd-ubuntu-packages/pull/8.

**Comment by nexus511** [comment]
Thank you.

Did you already check, if this still works with lightdm and Unity. I experienced that Unity produced some equal problems ignoring entries from the XML when there are multiple configuration entries.

**Comment by m-dango** [comment]
Yes, the xml works in both lightdm and Unity.

**Comment by sagebind** [comment]
FYI, GDM3 does not honor the xorg configuration because by default it uses Wayland in the login screen, even if you use Xorg after login. To force GDM3 to use Xorg (and share your Xorg config that the desktop uses), find and uncomment the line `WaylandEnable=false` in `/etc/gdm3/custom.conf`.

The alternative is to make the login session also use Wayland and get Wayland to rotate properly. This is what I am doing currently.

**Comment by nexus511** [comment]
@mienaikage Okay. I will update the packages then and try to build Ubuntu GNOME images upon that during the next days.

@sagebind As I guess that every change I made on any configuration will cause some trouble for someone in the future, I need to keep the amount of changes as low as possible. I have seen that @cawilliamson did indeed disable wayland actively. I guess I stick with the monitor.xml for now even this will fail if people already changed settings before it is updated.

**Comment by nexus511** [comment]
I have merged the commit to the development branch and added an updated package to the repository.

@sagebind I close this issue now but maybe we want to open another one supporting wayland properly. It might be worth adding another package to a testing repository that people can install if they want to have wayland.
