### ISSUE TITLE
How to use it for a installed ubuntu system(17.04, gnome 3,used cawilliamson's ansible)?

### ISSUE THREAD

**Issue by Xianbei233** [nexus511/gpd-ubuntu-packages#7]
RT. I want to used a stable ubuntu system and i found there is no plan for a installed ubuntu system.

**Comment by nexus511** [comment]
You need to remove the changes applied by the ansible scripts and then install the

- gpdpocket and
- gpdpocket-xfce-config and/or gpdpocket-gnome-congig.

See also http://apt.nexus511.net/posts/work-on-ubuntu-repository/
