### ISSUE TITLE
[REQUEST] Ubuntu Gnome

### ISSUE THREAD

**Issue by cawilliamson** [nexus511/gpd-ubuntu-packages#9]
Hey man,

Awesome work on this - just a quick (very cheeky) request from me!

Any chance of you adding Ubuntu GNOME to that list of supported ISOs?

It's quite popular since eventually all Ubuntu is going to be Ubuntu GNOME anyway so by setting it up now you're ensuring a seamless transition to 18.04 and beyond. 👍 

Cheers!

**Comment by nexus511** [comment]
@cawilliamson I understand.

I guess you have noticed #6 .

As soon as we figured that out, I can give it a try. I would assume that building it should be not a problem.

**Comment by cawilliamson** [comment]
... I can't believe I didn't check open issues before raising this.

I'm going to go hang my head in shame! :|

**Comment by nexus511** [comment]
@cawilliamson that are two things. I will also try to bootstrap an iso, if this works.

So leaving this open is basically a good idea.

**Comment by joedborg** [comment]
@cawilliamson, swapping Unity out for Gnome is quite simple.  Do you know how to do this?  If not I can help.

**Comment by nexus511** [comment]
@cawilliamson I have added ubuntu-gnome to the build and uploaded the images. Would be great if you had some time to test, if those boot and work.
